version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL
        - NEXT_PUBLIC_FIREBASE_API_KEY
        - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        - NEXT_PUBLIC_FIREBASE_PROJECT_ID
        - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        - NEXT_PUBLIC_FIREBASE_APP_ID
        - NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
      - NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}
    depends_on:
      - server
    networks:
      - app-network
    volumes:
      - ./client:/app

  server:
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CORS_ORIGINS=http://localhost:3000,http://client:3000
      - OPENAI_API_KEY=
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
