version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://server:8000
      - NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyCef_gbwRCZ7gZVz0ojblfSiDo_V-kneII
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=ta-ai-9ae49.firebaseapp.com
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=ta-ai-9ae49
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=ta-ai-9ae49.firebasestorage.app
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=174147167377
      - NEXT_PUBLIC_FIREBASE_APP_ID=1:174147167377:web:f29709dd39511bd8d00b30
      - NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=G-LTMFJS80RJ
    depends_on:
      - server
    networks:
      - app-network
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CORS_ORIGINS=http://localhost:3000,http://client:3000
      - OPENAI_API_KEY=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
      - FIREBASE_SERVICE_ACCOUNT_PATH=service_account.json
      - FIREBASE_STORAGE_BUCKET=ta-ai-9ae49.firebasestorage.app
    volumes:
      - ./server:/app
      - /app/__pycache__
      - /app/venv
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
