version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ai-ta-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_ta
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ai-ta-server
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ai_ta
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - UPLOAD_FOLDER=/app/uploads
    volumes:
      - ./server:/app
      - ./uploads:/app/uploads
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
